/**
 * Dedicated QA Integrity question pack.
 * Stable IDs with qa_ prefix. Never mixed into the 430-question library.
 */

import type { ConversationPromptDef } from "@/lib/conversations/response-types";

export const QA_PACK_VERSION = "qa-integrity-pack-v1";

export type QaExpectedCheck = {
  id: string;
  description: string;
};

export type QaQuestionDef = ConversationPromptDef & {
  test_case_id: string;
  expected_checks: QaExpectedCheck[];
  grouped_with?: string[];
  is_waiting_provider_case?: boolean;
  max_length?: number;
};

function opt(value: string, label?: string) {
  return { value, label: label ?? value };
}

export const QA_QUESTIONS: QaQuestionDef[] = [
  {
    id: "qa_quick_pick_same",
    test_case_id: "qa_1_same",
    version: QA_PACK_VERSION,
    prompt: "QA 1: Choose the same option",
    response_type: "quick_pick",
    answer_options: [opt("option_a", "Option A"), opt("option_b", "Option B"), opt("option_c", "Option C")],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "same_state", description: "State becomes answered_same" },
      { id: "no_diff", description: "No difference record is created" },
    ],
  },
  {
    id: "qa_quick_pick_different",
    test_case_id: "qa_2_different",
    version: QA_PACK_VERSION,
    prompt: "QA 2: Choose different options",
    response_type: "quick_pick",
    answer_options: [opt("morning", "Morning"), opt("night", "Night"), opt("neither", "Neither")],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "diff_state", description: "State becomes answered_different" },
      { id: "diff_record", description: "Difference record is created" },
      { id: "separate", description: "Both answers remain separate" },
    ],
  },
  {
    id: "qa_either_or",
    test_case_id: "qa_3_either_or",
    version: QA_PACK_VERSION,
    prompt: "QA 3: Either-Or test",
    response_type: "either_or",
    answer_options: [
      opt("choice_one", "Choice One"),
      opt("choice_two", "Choice Two"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "diff_review", description: "Difference review appears" },
      { id: "keep_both", description: "Keep both answers creates no shared answer" },
    ],
  },
  {
    id: "qa_short_text",
    test_case_id: "qa_4_short_text",
    version: QA_PACK_VERSION,
    prompt: "QA 4: Short-text persistence",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "persist", description: "Answers survive refresh, pause, resume, logout" },
    ],
  },
  {
    id: "qa_open_time_boxed",
    test_case_id: "qa_5_deep",
    version: QA_PACK_VERSION,
    prompt: "QA 5: Deep-answer persistence",
    response_type: "open_time_boxed",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 120,
    suggested_discussion_minutes: 2,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "coffee",
    conversation_tags: ["reflection"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "deep_persist", description: "Sam, Michelle, and shared deep answers persist" },
    ],
  },
  {
    id: "qa_reaction_scale",
    test_case_id: "qa_6_scale",
    version: QA_PACK_VERSION,
    prompt: "QA 6: Scale test",
    response_type: "reaction_scale",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    scale_min: 1,
    scale_max: 5,
    scale_low_label: "Strongly prefer first option",
    scale_high_label: "Strongly prefer second option",
    expected_checks: [
      { id: "numeric", description: "Scale values persist as numbers" },
      { id: "diff", description: "Difference state appears for 2 vs 4" },
    ],
  },
  {
    id: "qa_multi_select",
    test_case_id: "qa_7_multi",
    version: QA_PACK_VERSION,
    prompt: "QA 7: Multi-select test",
    response_type: "quick_pick",
    answer_options: [
      opt("alpha", "Alpha"),
      opt("beta", "Beta"),
      opt("gamma", "Gamma"),
      opt("delta", "Delta"),
    ],
    allow_multiple_selections: true,
    allow_custom_answer: false,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "no_dupes", description: "No duplicate options after reload" },
      { id: "order", description: "Option order remains stable" },
    ],
  },
  {
    id: "qa_custom_option",
    test_case_id: "qa_8_custom",
    version: QA_PACK_VERSION,
    prompt: "QA 8: Custom answer option test",
    response_type: "quick_pick",
    answer_options: [
      opt("existing_one", "Existing One"),
      opt("existing_two", "Existing Two"),
      opt("other", "Other"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "custom", description: "Custom text saves and returns exactly" },
    ],
  },
  {
    id: "qa_undecided",
    test_case_id: "qa_9_undecided",
    version: QA_PACK_VERSION,
    prompt: "QA 9: Undecided state test",
    response_type: "quick_pick",
    answer_options: [opt("yes", "Yes"), opt("no", "No")],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "undecided", description: "Undecided visible in review, not agreed, not unanswered" },
    ],
  },
  {
    id: "qa_discuss_later",
    test_case_id: "qa_10_later",
    version: QA_PACK_VERSION,
    prompt: "QA 10: Discuss Later state test",
    response_type: "open_time_boxed",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 60,
    suggested_discussion_minutes: 1,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "coffee",
    conversation_tags: ["reflection"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "later", description: "Discuss Later appears in summary and does not block completion" },
    ],
  },
  {
    id: "qa_waiting_provider",
    test_case_id: "qa_11_provider",
    version: QA_PACK_VERSION,
    prompt: "QA 11: Waiting for provider state test",
    response_type: "quick_pick",
    answer_options: [
      opt("ready", "Ready"),
      opt("need_provider", "Need provider input"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    is_waiting_provider_case: true,
    expected_checks: [
      { id: "provider", description: "Waiting for provider appears under provider questions" },
    ],
  },
  {
    id: "qa_grouped_a",
    test_case_id: "qa_12a_grouped",
    version: QA_PACK_VERSION,
    prompt: "QA 12A: Grouped screen first answer",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: 80,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    grouped_with: ["qa_grouped_b"],
    expected_checks: [
      { id: "independent_a", description: "Editing A does not alter B" },
    ],
  },
  {
    id: "qa_grouped_b",
    test_case_id: "qa_12b_grouped",
    version: QA_PACK_VERSION,
    prompt: "QA 12B: Grouped screen second answer",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: 80,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    grouped_with: ["qa_grouped_a"],
    expected_checks: [
      { id: "independent_b", description: "Editing B does not alter A" },
    ],
  },
  {
    id: "qa_quick_to_deep",
    test_case_id: "qa_13_quick",
    version: QA_PACK_VERSION,
    prompt: "QA 13: Quick-to-deep starting prompt",
    response_type: "quick_pick",
    answer_options: [opt("simple", "Simple"), opt("detailed", "Detailed")],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "qa_deep_follow_up",
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: true,
    active: true,
    expected_checks: [
      { id: "quick_kept", description: "Quick answer remains after deep" },
    ],
  },
  {
    id: "qa_deep_follow_up",
    test_case_id: "qa_13_deep",
    version: QA_PACK_VERSION,
    prompt: "QA 13 Deep Follow-Up",
    response_type: "open_time_boxed",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 90,
    suggested_discussion_minutes: 2,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "coffee",
    conversation_tags: ["reflection"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "deep_id", description: "Deep answer saves under qa_deep_follow_up" },
      { id: "resume", description: "Returning resumes at next card" },
    ],
  },
  {
    id: "qa_shared_answer",
    test_case_id: "qa_14_shared",
    version: QA_PACK_VERSION,
    prompt: "QA 14: Shared-answer creation",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 40,
    suggested_discussion_minutes: null,
    short_text_max_length: 200,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["partnership"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "three_values", description: "Sam, Michelle, and shared all remain" },
    ],
  },
  {
    id: "qa_edit_history",
    test_case_id: "qa_15_history",
    version: QA_PACK_VERSION,
    prompt: "QA 15: Revision history test",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "revisions", description: "Current is Version three; prior versions retained" },
    ],
  },
  {
    id: "qa_special_characters",
    test_case_id: "qa_16_special",
    version: QA_PACK_VERSION,
    prompt: "QA 16: Special characters and emoji",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: 200,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "chars", description: "Quotes, ampersand, emoji, newline without corruption" },
    ],
  },
  {
    id: "qa_long_valid_text",
    test_case_id: "qa_17_long",
    version: QA_PACK_VERSION,
    prompt: "QA 17: Long valid answer",
    response_type: "open_time_boxed",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 90,
    suggested_discussion_minutes: 2,
    short_text_max_length: 2000,
    follow_up_open_question_id: null,
    conversation_energy: "coffee",
    conversation_tags: ["reflection"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "long", description: "Long content saves complete after reload" },
    ],
  },
  {
    id: "qa_validation_limit",
    test_case_id: "qa_18_limit",
    version: QA_PACK_VERSION,
    prompt: "QA 18: Validation-limit test",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: 50,
    max_length: 50,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["warm_up"],
    session_tags: ["qa_integrity"],
    category: "qa",
    topic: "qa",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
    expected_checks: [
      { id: "block_51", description: "51-character answer blocked; 50 saves" },
    ],
  },
];

/** Fixed session order — never randomized. Grouped A/B share one card index via branch. */
export const QA_SESSION_ORDER: string[] = [
  "qa_quick_pick_same",
  "qa_quick_pick_different",
  "qa_either_or",
  "qa_short_text",
  "qa_open_time_boxed",
  "qa_reaction_scale",
  "qa_multi_select",
  "qa_custom_option",
  "qa_undecided",
  "qa_discuss_later",
  "qa_waiting_provider",
  "qa_grouped_a", // grouped_b rendered on same card
  "qa_quick_to_deep",
  "qa_deep_follow_up",
  "qa_shared_answer",
  "qa_edit_history",
  "qa_special_characters",
  "qa_long_valid_text",
  "qa_validation_limit",
];

export const QA_SUGGESTED_TASK_TITLES = [
  "QA Task One",
  "QA Task Two",
  "QA Provider Follow-Up",
  "QA Discuss-Later Follow-Up",
] as const;

export const QA_EXPECTED = {
  short_sam: "Sam QA short answer 123",
  short_michelle: "Michelle QA short answer 456",
  deep_sam: "Sam deep answer test. This text must remain unchanged.",
  deep_michelle: "Michelle deep answer test. This text must remain unchanged.",
  deep_shared: "Shared QA answer. Preserve separate answers too.",
  custom: "Custom QA Choice",
  grouped_a: "Grouped answer A",
  grouped_b: "Grouped answer B",
  deep_follow_up: "QA deep follow-up answer",
  shared_sam: "Sam position",
  shared_michelle: "Michelle position",
  shared_agreed: "QA agreed position",
  history_versions: ["Version one", "Version two", "Version three"],
  special:
    "QA “quotes” apostrophe's ampersand & emoji 👶 ❤️ newline test",
  trip_memory: "QA trip memory: storage test completed",
} as const;

export function getQaQuestion(id: string): QaQuestionDef | undefined {
  return QA_QUESTIONS.find((q) => q.id === id);
}

export function isQaQuestionId(id: string): boolean {
  return id.startsWith("qa_");
}

export function qaQuestionCount(): number {
  return QA_QUESTIONS.length;
}
