import type { ConversationPromptDef } from "./response-types";

const V = "conversation-prompts-v1";

function opt(value: string, label?: string) {
  return { value, label: label ?? value };
}

/** Curated quick prompts — stable IDs, safe for Trip Mode and remote store. */
export const QUICK_PROMPTS: ConversationPromptDef[] = [
  // —— Foundation and values ——
  {
    id: "qp_parent_word",
    version: V,
    prompt: "One word for the parent you want to be.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: 40,
    follow_up_open_question_id: "q_what_does_success_as_parents_mean_to_us",
    conversation_energy: "lightning",
    conversation_tags: ["warm_up", "identity", "values"],
    session_tags: ["babymoon_set_v1", "companion_success"],
    category: "foundation",
    topic: "identity",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_calm_or_consistency",
    version: V,
    prompt: "Which matters more in a hard moment: calm or consistency?",
    response_type: "either_or",
    answer_options: [
      opt("calm", "Calm"),
      opt("consistency", "Consistency"),
      opt("depends", "It depends"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_does_a_loving_home_look_and_feel_like_to_us",
    conversation_energy: "lightning",
    conversation_tags: ["values", "partnership"],
    session_tags: [],
    category: "foundation",
    topic: "values",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_cautious_or_reckless",
    version: V,
    prompt: "Which worries you more: too cautious or too reckless?",
    response_type: "either_or",
    answer_options: [
      opt("too_cautious", "Too cautious"),
      opt("too_reckless", "Too reckless"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["values", "identity"],
    session_tags: [],
    category: "foundation",
    topic: "values",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_success_age_eight",
    version: V,
    prompt: "What should success feel like for our child at age eight?",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 35,
    suggested_discussion_minutes: null,
    short_text_max_length: 120,
    follow_up_open_question_id: "q_what_does_success_as_parents_mean_to_us",
    conversation_energy: "lightning",
    conversation_tags: ["values", "identity"],
    session_tags: [],
    category: "foundation",
    topic: "values",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_kindness_or_achievement",
    version: V,
    prompt: "Which matters more: kindness or achievement?",
    response_type: "either_or",
    answer_options: [
      opt("kindness", "Kindness"),
      opt("achievement", "Achievement"),
      opt("both", "Both, in balance"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_traits_do_we_most_hope_our_child_develops",
    conversation_energy: "lightning",
    conversation_tags: ["values"],
    session_tags: [],
    category: "foundation",
    topic: "values",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_home_feel",
    version: V,
    prompt: "What should our home feel like most often?",
    response_type: "quick_pick",
    answer_options: [
      opt("calm", "Calm"),
      opt("playful", "Playful"),
      opt("structured", "Structured"),
      opt("warm", "Warm and busy"),
      opt("flexible", "Flexible"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_does_a_loving_home_look_and_feel_like_to_us",
    conversation_energy: "lightning",
    conversation_tags: ["identity", "family"],
    session_tags: [],
    category: "foundation",
    topic: "identity",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_value_to_model",
    version: V,
    prompt: "One value our child should see us model.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: 60,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["values"],
    session_tags: [],
    category: "foundation",
    topic: "values",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_childhood_repeat",
    version: V,
    prompt: "One childhood experience we want to repeat.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id:
      "q_what_parts_of_our_own_childhoods_do_we_hope_to_repeat",
    conversation_energy: "lightning",
    conversation_tags: ["identity", "traditions"],
    session_tags: [],
    category: "foundation",
    topic: "identity",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_childhood_change",
    version: V,
    prompt: "One childhood pattern we want to change.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id:
      "q_what_parts_of_our_own_childhoods_do_we_hope_to_repeat",
    conversation_energy: "lightning",
    conversation_tags: ["identity", "reflection"],
    session_tags: [],
    category: "foundation",
    topic: "identity",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },

  // —— Birth and first weeks ——
  {
    id: "qp_birth_room_word",
    version: V,
    prompt: "One word for what you want the birth room to feel like.",
    response_type: "quick_pick",
    answer_options: [
      opt("calm", "Calm"),
      opt("private", "Private"),
      opt("supported", "Supported"),
      opt("efficient", "Efficient"),
      opt("flexible", "Flexible"),
      opt("safe", "Safe"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_role_should_each_parent_have_during_labor",
    conversation_energy: "lightning",
    conversation_tags: ["birth", "warm_up"],
    session_tags: ["babymoon_set_v1", "companion_birth"],
    category: "birth",
    topic: "birth",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_first_week_home",
    version: V,
    prompt: "First week home?",
    response_type: "quick_pick",
    answer_options: [
      opt("closed_door", "Closed door"),
      opt("close_family", "Close family only"),
      opt("planned_visits", "Planned short visits"),
      opt("open_door", "Open door"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_accepting_or_declining_visitors_in_week_o",
    conversation_energy: "lightning",
    conversation_tags: ["visitors", "family"],
    session_tags: ["babymoon_set_v1", "companion_visitors"],
    category: "birth",
    topic: "visitors",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_hospital_updates",
    version: V,
    prompt: "Who communicates hospital updates?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "Both, as needed"),
      opt("designated", "One designated person"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_should_family_members_receive_updates_during_labor_and_bir",
    conversation_energy: "lightning",
    conversation_tags: ["birth", "family"],
    session_tags: [],
    category: "birth",
    topic: "birth",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_night_person",
    version: V,
    prompt: "Who is naturally the night person?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("neither", "Neither"),
      opt("unclear", "Unclear"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_should_we_divide_overnight_care_in_the_first_weeks",
    conversation_energy: "lightning",
    conversation_tags: ["sleep", "partnership"],
    session_tags: ["babymoon_set_v1", "companion_overnight"],
    category: "birth",
    topic: "sleep",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_morning_person",
    version: V,
    prompt: "Who is naturally the morning person?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("neither", "Neither"),
      opt("unclear", "Unclear"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_should_we_divide_overnight_care_in_the_first_weeks",
    conversation_energy: "lightning",
    conversation_tags: ["sleep", "partnership"],
    session_tags: ["babymoon_set_v1", "companion_labor_division"],
    category: "birth",
    topic: "sleep",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_visitors_bring",
    version: V,
    prompt: "Visitors should bring: food, help, or company?",
    response_type: "quick_pick",
    answer_options: [
      opt("food", "Food"),
      opt("help", "Help"),
      opt("company", "Company"),
      opt("depends", "Depends on the visit"),
      opt("nothing", "Nothing required"),
    ],
    allow_multiple_selections: true,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_does_a_calm_postpartum_home_environment_require_from_visi",
    conversation_energy: "lightning",
    conversation_tags: ["visitors", "family"],
    session_tags: [],
    category: "birth",
    topic: "visitors",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_ask_before_holding",
    version: V,
    prompt: "Ask before holding the baby?",
    response_type: "either_or",
    answer_options: [
      opt("yes", "Yes, always ask"),
      opt("close_only", "Close family can skip asking"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_accepting_or_declining_visitors_in_week_o",
    conversation_energy: "lightning",
    conversation_tags: ["visitors", "privacy"],
    session_tags: [],
    category: "birth",
    topic: "visitors",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_hospital_photos",
    version: V,
    prompt: "Photos at the hospital: yes, limited, or none?",
    response_type: "quick_pick",
    answer_options: [
      opt("yes", "Yes"),
      opt("limited", "Limited"),
      opt("none", "None during labor"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_do_we_want_to_handle_photos_and_social_media_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["privacy", "birth"],
    session_tags: [],
    category: "birth",
    topic: "privacy",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_advice_default",
    version: V,
    prompt: "Our default response to unsolicited advice?",
    response_type: "quick_pick",
    answer_options: [
      opt("nod", "Nod and move on"),
      opt("polite", "Polite pushback"),
      opt("boundary", "Clear boundary"),
      opt("depends", "Depends on the person"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_how_should_we_handle_unsolicited_parenting_advice",
    conversation_energy: "lightning",
    conversation_tags: ["advice", "partnership"],
    session_tags: ["babymoon_set_v1", "companion_advice"],
    category: "birth",
    topic: "advice",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_feeding_start",
    version: V,
    prompt: "Our starting approach feels closest to:",
    response_type: "quick_pick",
    answer_options: [
      opt("nursing", "Nursing first"),
      opt("combination", "Combination"),
      opt("formula", "Formula"),
      opt("flexible", "Flexible"),
      opt("unsure", "Unsure"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_approach_to_feeding_in_the_newborn_stage",
    conversation_energy: "lightning",
    conversation_tags: ["feeding"],
    session_tags: ["companion_feeding"],
    category: "birth",
    topic: "feeding",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },

  // —— Partnership ——
  {
    id: "qp_solve_or_listen",
    version: V,
    prompt: "Which feels more supportive: solving the problem or listening first?",
    response_type: "either_or",
    answer_options: [
      opt("solve", "Solving the problem"),
      opt("listen", "Listening first"),
      opt("depends", "It depends"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_does_a_good_day_look_like_when_both_parents_are_exhausted",
    conversation_energy: "lightning",
    conversation_tags: ["partnership"],
    session_tags: [],
    category: "partnership",
    topic: "partnership",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_notices_supplies",
    version: V,
    prompt: "Who notices household supplies first?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "Both about equally"),
      opt("unclear", "Unclear"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["partnership"],
    session_tags: [],
    category: "partnership",
    topic: "partnership",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_family_comms",
    version: V,
    prompt: "Who handles family communication more naturally?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "We share it"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_role_do_we_want_grandparents_to_play",
    conversation_energy: "lightning",
    conversation_tags: ["partnership", "family"],
    session_tags: [],
    category: "partnership",
    topic: "partnership",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_conflict_style",
    version: V,
    prompt: "In conflict: pause first or finish the discussion?",
    response_type: "either_or",
    answer_options: [
      opt("pause", "Pause first"),
      opt("finish", "Finish the discussion"),
      opt("depends", "It depends"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_should_we_handle_parenting_disagreements_in_front_of_our_c",
    conversation_energy: "lightning",
    conversation_tags: ["partnership"],
    session_tags: [],
    category: "partnership",
    topic: "partnership",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_relief_phrase",
    version: V,
    prompt: "One phrase each person may use to ask for relief.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 80,
    follow_up_open_question_id:
      "q_how_will_we_check_in_weekly_about_parenting_stress",
    conversation_energy: "lightning",
    conversation_tags: ["partnership"],
    session_tags: [],
    category: "partnership",
    topic: "partnership",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_fairness_or_recovery",
    version: V,
    prompt: "Which matters more after a hard night: fairness or recovery needs?",
    response_type: "either_or",
    answer_options: [
      opt("fairness", "Fairness"),
      opt("recovery", "Recovery needs"),
      opt("both", "Both, case by case"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_should_we_divide_overnight_care_in_the_first_weeks",
    conversation_energy: "lightning",
    conversation_tags: ["partnership", "sleep"],
    session_tags: [],
    category: "partnership",
    topic: "partnership",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },

  // —— Traditions ——
  {
    id: "qp_holiday_size",
    version: V,
    prompt: "Big holiday gathering or small quiet one?",
    response_type: "either_or",
    answer_options: [
      opt("big", "Big gathering"),
      opt("small", "Small quiet gathering"),
      opt("depends", "Depends on the holiday"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "holidays", "family"],
    session_tags: ["babymoon_set_v1", "companion_holidays"],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_family_food",
    version: V,
    prompt: "Pick one food from your childhood to become our family’s food.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: 80,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "fun"],
    session_tags: ["babymoon_set_v1"],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_holiday_excited",
    version: V,
    prompt: "One holiday each person is excited to share.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: 60,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "holidays"],
    session_tags: [],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_trip_or_home_tradition",
    version: V,
    prompt: "Annual trip or annual home tradition?",
    response_type: "either_or",
    answer_options: [
      opt("trip", "Annual trip"),
      opt("home", "Annual home tradition"),
      opt("both", "Both if we can"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "fun"],
    session_tags: [],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_matching_pajamas",
    version: V,
    prompt: "Matching pajamas: yes or no?",
    response_type: "either_or",
    answer_options: [
      opt("yes", "Yes"),
      opt("no", "No"),
      opt("sometimes", "Sometimes"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "fun"],
    session_tags: [],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_family_motto",
    version: V,
    prompt: "If our family had a motto, what would it say?",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["identity", "values", "wrap_up"],
    session_tags: ["babymoon_set_v1"],
    category: "traditions",
    topic: "identity",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_sam_tradition",
    version: V,
    prompt: "One tradition from Sam’s family worth keeping.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "family"],
    session_tags: [],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_michelle_tradition",
    version: V,
    prompt: "One tradition from Michelle’s family worth keeping.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 30,
    suggested_discussion_minutes: null,
    short_text_max_length: 100,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["traditions", "family"],
    session_tags: [],
    category: "traditions",
    topic: "traditions",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },

  // —— Privacy ——
  {
    id: "qp_baby_face_online",
    version: V,
    prompt: "Baby’s face on social media?",
    response_type: "quick_pick",
    answer_options: [
      opt("public", "Public posts are fine"),
      opt("close_friends", "Close friends only"),
      opt("private_family", "Private family sharing only"),
      opt("no_face", "No face online"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_do_we_want_to_handle_photos_and_social_media_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["privacy"],
    session_tags: ["babymoon_set_v1", "companion_social"],
    category: "privacy",
    topic: "privacy",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_birth_details_share",
    version: V,
    prompt: "Birth details shared widely or privately?",
    response_type: "either_or",
    answer_options: [
      opt("widely", "Widely with close circle"),
      opt("privately", "Privately"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_do_we_want_to_handle_photos_and_social_media_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["privacy", "birth"],
    session_tags: [],
    category: "privacy",
    topic: "privacy",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_group_chat_or_album",
    version: V,
    prompt: "Family group chat or private photo album?",
    response_type: "either_or",
    answer_options: [
      opt("group_chat", "Family group chat"),
      opt("album", "Private photo album"),
      opt("both", "Both"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_do_we_want_to_handle_photos_and_social_media_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["privacy", "family"],
    session_tags: [],
    category: "privacy",
    topic: "privacy",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_grandparents_posting",
    version: V,
    prompt: "Grandparents posting photos?",
    response_type: "quick_pick",
    answer_options: [
      opt("ok", "Okay with our rules"),
      opt("ask_first", "Ask us first"),
      opt("no", "Please don’t post"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_do_we_want_to_handle_photos_and_social_media_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["privacy", "family"],
    session_tags: [],
    category: "privacy",
    topic: "privacy",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_visitor_notice",
    version: V,
    prompt: "Do visitors need advance notice?",
    response_type: "either_or",
    answer_options: [
      opt("yes", "Yes"),
      opt("close_flexible", "Close family can be flexible"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_accepting_or_declining_visitors_in_week_o",
    conversation_energy: "lightning",
    conversation_tags: ["visitors"],
    session_tags: [],
    category: "privacy",
    topic: "visitors",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_visitor_job",
    version: V,
    prompt: "Do visitors need a job, such as food or laundry?",
    response_type: "either_or",
    answer_options: [
      opt("yes", "Yes, a helpful job"),
      opt("optional", "Helpful but optional"),
      opt("no", "Company is enough"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_does_a_calm_postpartum_home_environment_require_from_visi",
    conversation_energy: "lightning",
    conversation_tags: ["visitors"],
    session_tags: [],
    category: "privacy",
    topic: "visitors",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },

  // —— Lulu ——
  {
    id: "qp_lulu_nursery",
    version: V,
    prompt: "Lulu in the nursery?",
    response_type: "quick_pick",
    answer_options: [
      opt("yes_supervised", "Yes, supervised"),
      opt("doorway", "Doorway only at first"),
      opt("not_yet", "Not yet"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_safety_rules_apply_to_pets_and_the_baby",
    conversation_energy: "lightning",
    conversation_tags: ["lulu"],
    session_tags: ["companion_lulu"],
    category: "lulu",
    topic: "lulu",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_lulu_feeding",
    version: V,
    prompt: "Lulu near feeding areas?",
    response_type: "quick_pick",
    answer_options: [
      opt("ok", "Okay nearby"),
      opt("crate_or_gate", "Crate or gate during feeds"),
      opt("another_room", "Another room"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: "q_what_safety_rules_apply_to_pets_and_the_baby",
    conversation_energy: "lightning",
    conversation_tags: ["lulu", "feeding"],
    session_tags: [],
    category: "lulu",
    topic: "lulu",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_lulu_intro",
    version: V,
    prompt: "Who handles the first introduction?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "Both together"),
      opt("undecided", "Undecided"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_how_should_we_prepare_siblings_or_pets_if_relevant_for_the_bab",
    conversation_energy: "lightning",
    conversation_tags: ["lulu"],
    session_tags: [],
    category: "lulu",
    topic: "lulu",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_stroller_walk",
    version: V,
    prompt: "Stroller walk before birth?",
    response_type: "either_or",
    answer_options: [
      opt("yes", "Yes"),
      opt("optional", "Nice but optional"),
      opt("no", "Not needed"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_pet_care_and_home_logistics_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["lulu", "fun"],
    session_tags: [],
    category: "lulu",
    topic: "lulu",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: false,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_primary_dog_sitter",
    version: V,
    prompt: "Primary dog sitter?",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: 60,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_pet_care_and_home_logistics_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["lulu"],
    session_tags: [],
    category: "lulu",
    topic: "lulu",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
  },
  {
    id: "qp_backup_sitter",
    version: V,
    prompt: "Backup sitter confirmed?",
    response_type: "either_or",
    answer_options: [
      opt("yes", "Yes"),
      opt("in_progress", "Still confirming"),
      opt("no", "Not yet"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_pet_care_and_home_logistics_after_birth",
    conversation_energy: "lightning",
    conversation_tags: ["lulu"],
    session_tags: [],
    category: "lulu",
    topic: "lulu",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: false,
    is_conversation_companion: true,
    active: true,
  },

  // —— Fun ——
  {
    id: "qp_first_vacation",
    version: V,
    prompt: "First family vacation style?",
    response_type: "quick_pick",
    answer_options: [
      opt("beach", "Beach"),
      opt("city", "City"),
      opt("mountains", "Mountains"),
      opt("road_trip", "Road trip"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun", "traditions"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_first_splurge",
    version: V,
    prompt: "First major splurge?",
    response_type: "quick_pick",
    answer_options: [
      opt("travel", "Travel"),
      opt("photos", "Photos"),
      opt("gear", "Gear"),
      opt("savings", "Savings"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 15,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun", "money"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_first_book",
    version: V,
    prompt: "Favorite children’s book to share first.",
    response_type: "short_text",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: true,
    estimated_time_seconds: 25,
    suggested_discussion_minutes: null,
    short_text_max_length: 80,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun", "traditions"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_silly_voices",
    version: V,
    prompt: "Which parent handles silly voices?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "Both"),
      opt("neither", "Neither of us yet"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun", "partnership"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_overpack",
    version: V,
    prompt: "Which parent is more likely to overpack?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "Both of us"),
      opt("neither", "Neither"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_break_rule_fun",
    version: V,
    prompt: "Which parent is more likely to break a rule for fun?",
    response_type: "quick_pick",
    answer_options: [
      opt("sam", "Sam"),
      opt("michelle", "Michelle"),
      opt("both", "Both"),
      opt("neither", "Neither"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_dinner_or_adventure",
    version: V,
    prompt: "Family dinner or weekend adventure?",
    response_type: "either_or",
    answer_options: [
      opt("dinner", "Family dinner"),
      opt("adventure", "Weekend adventure"),
      opt("both", "Both matter"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun", "traditions"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_museum_or_outdoor",
    version: V,
    prompt: "Museum day or outdoor day?",
    response_type: "either_or",
    answer_options: [
      opt("museum", "Museum day"),
      opt("outdoor", "Outdoor day"),
      opt("depends", "Depends on the week"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: false,
    is_conversation_companion: false,
    active: true,
  },
  {
    id: "qp_structured_weekend",
    version: V,
    prompt: "Structured weekend or spontaneous weekend?",
    response_type: "either_or",
    answer_options: [
      opt("structured", "Structured"),
      opt("spontaneous", "Spontaneous"),
      opt("mix", "A mix"),
    ],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 10,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id: null,
    conversation_energy: "lightning",
    conversation_tags: ["fun", "identity"],
    session_tags: [],
    category: "fun",
    topic: "fun",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: true,
    show_difference_prompt: true,
    is_conversation_companion: false,
    active: true,
  },

  // —— Reaction scale sample ——
  {
    id: "qp_visitor_energy",
    version: V,
    prompt: "How protective do you feel about early visitor boundaries?",
    response_type: "reaction_scale",
    answer_options: [],
    allow_multiple_selections: false,
    allow_custom_answer: false,
    estimated_time_seconds: 20,
    suggested_discussion_minutes: null,
    short_text_max_length: null,
    follow_up_open_question_id:
      "q_what_is_our_plan_for_accepting_or_declining_visitors_in_week_o",
    conversation_energy: "lightning",
    conversation_tags: ["visitors"],
    session_tags: [],
    category: "privacy",
    topic: "visitors",
    life_stage: "before_birth",
    supports_separate_answers: true,
    supports_shared_answer: false,
    show_difference_prompt: true,
    is_conversation_companion: true,
    active: true,
    scale_min: 1,
    scale_max: 5,
    scale_low_label: "Open and easy",
    scale_high_label: "Very protective",
  },
];

export function getQuickPrompt(id: string): ConversationPromptDef | undefined {
  return QUICK_PROMPTS.find((p) => p.id === id && p.active);
}

export function getActiveQuickPrompts(): ConversationPromptDef[] {
  return QUICK_PROMPTS.filter((p) => p.active);
}

export function getCompanionForDeepQuestion(
  questionId: string,
): ConversationPromptDef | undefined {
  return QUICK_PROMPTS.find(
    (p) => p.active && p.is_conversation_companion && p.follow_up_open_question_id === questionId,
  );
}

export function countQuickToDeepLinks(): number {
  return QUICK_PROMPTS.filter((p) => p.active && p.follow_up_open_question_id).length;
}
