import {
  registerChecklistTemplate,
  type ChecklistTemplateDef,
} from "@/lib/checklists/types";

function section(
  slug: string,
  label: string,
  sort_order: number,
  titles: string[],
  priority: "high" | "medium" | "low" = "medium",
): ChecklistTemplateDef["sections"][number] {
  return {
    slug,
    label,
    sort_order,
    tasks: titles.map((title, index) => ({
      slug: `${slug}_${index + 1}`,
      title,
      priority,
    })),
  };
}

export const BEFORE_BABY_TEMPLATE: ChecklistTemplateDef = {
  slug: "before-baby",
  title: "Before Baby",
  description:
    "A practical checklist of everything to finish before the baby arrives — hospital, home, gear, paperwork, and the final week.",
  sections: [
    section(
      "hospital_birth",
      "Hospital & Birth",
      1,
      [
        "Choose delivering hospital",
        "Complete hospital registration",
        "Confirm insurance coverage",
        "Tour hospital",
        "Install infant car seat",
        "Get car seat inspected",
        "Pack hospital bag for Michelle",
        "Pack hospital bag for Sam",
        "Prepare snacks for hospital",
        "Install infant mirror",
        "Save pediatrician phone number",
        "Save OB emergency number",
        "Know route to hospital",
        "Create birth plan",
        "Print birth plan",
        "Discuss visitors during labor",
        "Decide cord blood banking",
        "Decide circumcision if applicable",
      ],
      "high",
    ),
    section(
      "medical",
      "Medical",
      2,
      [
        "Choose pediatrician",
        "Schedule first pediatrician appointment",
        "Understand vaccine schedule",
        "Complete prenatal classes",
        "CPR class",
        "Infant choking class",
        "Know after-hours pediatrician process",
      ],
      "high",
    ),
    section(
      "home",
      "Home",
      3,
      [
        "Assemble crib",
        "Assemble bassinet",
        "Install monitor",
        "Install blackout curtains",
        "Wash baby clothes",
        "Wash swaddles",
        "Wash crib sheets",
        "Baby-proof important areas",
        "Organize changing station",
        "Set up diaper station",
        "Set up feeding station",
        "Freeze meals",
        "Stock pantry",
        "Install night lights",
      ],
    ),
    section(
      "baby_gear",
      "Baby Gear",
      4,
      [
        "Car seat",
        "Stroller",
        "Baby carrier",
        "Bassinet",
        "Crib",
        "Mattress",
        "Waterproof mattress protector",
        "Changing pad",
        "Diaper pail",
        "Baby monitor",
        "White noise machine",
        "Thermometer",
        "Nasal aspirator",
        "Baby nail clippers",
        "Bottles",
        "Bottle brush",
        "Drying rack",
        "Breast pump",
        "Pump accessories",
        "Formula (if desired)",
        "Pacifiers",
        "Swaddles",
        "Sleep sacks",
      ],
    ),
    section(
      "paperwork",
      "Paperwork",
      5,
      [
        "Review parental leave",
        "File FMLA if needed",
        "Add baby to insurance checklist",
        "Review life insurance",
        "Update beneficiaries",
        "Create or update will",
        "Emergency contacts updated",
        "Guardians chosen",
        "Hospital pre-registration complete",
      ],
      "high",
    ),
    section(
      "financial",
      "Financial",
      6,
      [
        "Estimate first-year budget",
        "Open baby savings account (optional)",
        "Increase emergency fund if desired",
        "Purchase remaining baby items",
        "Understand childcare costs",
      ],
    ),
    section(
      "relationship",
      "Relationship",
      7,
      [
        "Plan first month meal strategy",
        "Discuss overnight responsibilities",
        "Discuss visiting family expectations",
        "Schedule one date before due date",
        "Discuss communication during stressful nights",
      ],
    ),
    section(
      "pets",
      "Pets",
      8,
      [
        "Prepare Lulu",
        "Practice stroller walks",
        "Create dog care plan during delivery",
        "Arrange backup dog sitter",
      ],
    ),
    section(
      "final_week",
      "Final Week",
      9,
      [
        "Charge cameras",
        "Charge phones",
        "Fuel car",
        "Install car seat",
        "Hospital bags in car",
        "Laundry complete",
        "House cleaned",
        "Refrigerator stocked",
        "Confirm pediatrician",
        "Relax together",
      ],
      "high",
    ),
  ],
};

registerChecklistTemplate(BEFORE_BABY_TEMPLATE);
