import {
  registerChecklistTemplate,
  type ChecklistTemplateDef,
} from "@/lib/checklists/types";

function section(
  slug: string,
  label: string,
  sort_order: number,
  titles: string[],
  priority: "high" | "medium" | "low" = "medium",
): ChecklistTemplateDef["sections"][number] {
  return {
    slug,
    label,
    sort_order,
    tasks: titles.map((title, index) => ({
      slug: `${slug}_${index + 1}`,
      title,
      priority,
    })),
  };
}

export const BEFORE_BABY_TEMPLATE: ChecklistTemplateDef = {
  slug: "before-baby",
  title: "Before Baby",
  description:
    "A practical checklist of everything to finish before the baby arrives — hospital, home, gear, paperwork, and the final week.",
  sections: [
    section(
      "hospital_birth",
      "Hospital & Birth",
      1,
      [
        "Choose delivering hospital",
        "Complete hospital registration",
        "Confirm insurance coverage",
        "Tour hospital",
        "Install infant car seat",
        "Get car seat inspected",
        "Pack hospital bag for Michelle",
        "Pack hospital bag for Sam",
        "Prepare snacks for hospital",
        "Install infant mirror",
        "Save pediatrician phone number",
        "Save OB emergency number",
        "Know route to hospital",
        "Create birth plan",
        "Print birth plan",
        "Discuss visitors during labor",
        "Decide cord blood banking",
        "Decide circumcision if applicable",
        "Discuss pain management preferences",
        "Decide who is present during delivery",
        "Discuss photo/video policy during birth and recovery",
      ],
      "high",
    ),
    section(
      "medical",
      "Medical",
      2,
      [
        "Choose pediatrician",
        "Schedule first pediatrician appointment",
        "Understand vaccine schedule",
        "Complete prenatal classes",
        "CPR class",
        "Infant choking class",
        "Know after-hours pediatrician process",
        "Decide feeding approach (breastfeeding, formula, or combination)",
        "Take a newborn care basics class (bathing, diapering, swaddling)",
      ],
      "high",
    ),
    section(
      "home",
      "Home",
      3,
      [
        "Assemble crib",
        "Assemble bassinet",
        "Install monitor",
        "Install blackout curtains",
        "Wash baby clothes",
        "Wash swaddles",
        "Wash crib sheets",
        "Baby-proof important areas",
        "Organize changing station",
        "Set up diaper station",
        "Set up feeding station",
        "Freeze meals",
        "Stock pantry",
        "Install night lights",
      ],
    ),
    section(
      "baby_gear",
      "Baby Gear",
      4,
      [
        "Car seat",
        "Stroller",
        "Baby carrier",
        "Bassinet",
        "Crib",
        "Mattress",
        "Waterproof mattress protector",
        "Changing pad",
        "Diaper pail",
        "Baby monitor",
        "White noise machine",
        "Thermometer",
        "Nasal aspirator",
        "Baby nail clippers",
        "Bottles",
        "Bottle brush",
        "Drying rack",
        "Breast pump",
        "Pump accessories",
        "Formula (if desired)",
        "Pacifiers",
        "Swaddles",
        "Sleep sacks",
        "Going-home outfit for baby",
      ],
    ),
    section(
      "paperwork",
      "Paperwork",
      5,
      [
        "Review parental leave",
        "File FMLA if needed",
        "Add baby to insurance checklist",
        "Review life insurance",
        "Update beneficiaries",
        "Create or update will",
        "Emergency contacts updated",
        "Guardians chosen",
        "Hospital pre-registration complete",
      ],
      "high",
    ),
    section(
      "financial",
      "Financial",
      6,
      [
        "Estimate first-year budget",
        "Open baby savings account (optional)",
        "Increase emergency fund if desired",
        "Purchase remaining baby items",
        "Understand childcare costs",
      ],
    ),
    section(
      "relationship",
      "Relationship",
      7,
      [
        "Plan first month meal strategy",
        "Discuss overnight responsibilities",
        "Discuss visiting family expectations",
        "Schedule one date before due date",
        "Discuss communication during stressful nights",
        "Learn postpartum depression/anxiety warning signs for both parents",
      ],
    ),
    section(
      "pets",
      "Pets",
      8,
      [
        "Prepare Lulu",
        "Practice stroller walks",
        "Create dog care plan during delivery",
        "Arrange backup dog sitter",
      ],
    ),
    section(
      "work_leave",
      "Work & Leave",
      9,
      [
        "Document Sam work handoff",
        "Document Michelle work handoff if applicable",
        "Confirm leave dates",
        "Submit employer paperwork",
        "Set return-to-work reminder",
        "Confirm childcare start date",
        "Confirm drop-off and pickup plan",
        "Create backup childcare plan",
      ],
      "high",
    ),
    section(
      "postpartum_prep",
      "Postpartum preparation",
      10,
      [
        "Save labor and delivery triage number",
        "Save OB urgent contact instructions",
        "Prepare postpartum recovery supplies",
        "Confirm postpartum follow-up process",
        "Identify lactation support if relevant",
        "Create medication and allergy list",
        "Create emergency contact list",
        "Arrange help schedule for the first two weeks (meals, visitors, chores)",
        "Decide whether to use a postpartum doula or night nurse",
      ],
      "high",
    ),
    section(
      "legal_extra",
      "Legal & documents",
      11,
      [
        "Review beneficiary designations",
        "Store legal documents securely",
        "Tell trusted person where documents are stored",
        "Decide education savings approach",
        "Create post-birth education savings task if chosen",
        "Update beneficiary designations where needed",
      ],
      "high",
    ),
    section(
      "lulu_extra",
      "Lulu details",
      12,
      [
        "Confirm primary sitter",
        "Confirm backup sitter",
        "Share written care instructions",
        "Practice baby-area boundaries",
        "Prepare first introduction",
        "Confirm Lulu labor plan",
      ],
    ),
    section(
      "home_extra",
      "Home readiness",
      13,
      [
        "Remove unsafe items from sleep space",
        "Safe sleep final check",
        "Complete final house reset",
      ],
    ),
    section(
      "final_week",
      "Final Week",
      14,
      [
        "Charge cameras",
        "Charge phones",
        "Fuel car",
        "Confirm car seat install in vehicle",
        "Hospital bags in car",
        "Confirm laundry and sheets reset",
        "Complete light house reset check",
        "Refresh groceries",
        "Confirm pediatrician contact",
        "Rest and reduce workload",
        "Confirm dog sitter",
        "Confirm hospital route",
      ],
      "high",
    ),
    section(
      "announcements_and_support",
      "Announcements & support network",
      15,
      [
        "Decide who to call first after birth",
        "Plan birth announcement (family, friends, social media)",
        "Identify backup emergency contact if both parents are unavailable",
      ],
    ),
  ],
};

registerChecklistTemplate(BEFORE_BABY_TEMPLATE);
